version: '3.8'

services:
  freepics:
    image: maomao12436/freepics:latest
    container_name: freepics-server
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - uploads_data:/app/uploads
      - config_data:/app/config
      - ./ssl:/app/ssl
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/uploads
      - CONFIG_PATH=/app/config
      - PORT=5000
    restart: unless-stopped
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: freepics-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - freepics
    restart: unless-stopped

volumes:
  uploads_data:
    driver: local
  config_data:
    driver: local
